# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('access_level', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last_login')),
            ],
        ),
    ]
