# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
