# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20160130_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 30, 19, 43, 21, 548461, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
