# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160204_0327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Attr',
        ),
    ]
